import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileExists, findFilePath } from '../lib/helpers'
import { logger as _logger } from '../lib/logger'

const logger = _logger.withTag('change-font')

const NEW_LAYOUT_CONTENT = `import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const fontSans = Inter({
    variable: '--font-inter',
    subsets: ['latin'],
    weight: ['400', '700'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={\`\${fontSans.variable} antialiased font-sans\`}>
                {children}
            </body>
        </html>
    )
}
`

const NEW_GLOBALS_CSS_CONTENT = `@import 'tailwindcss';

:root {
    --background: #ffffff;
    --foreground: #171717;
}

@theme inline {
    --color-background: var(--background);
    --color-foreground: var(--foreground);
    --font-sans: var(--font-inter);
}

@media (prefers-color-scheme: dark) {
    :root {
        --background: #0a0a0a;
        --foreground: #ededed;
    }
}

body {
    background: var(--background);
    color: var(--foreground);
}
`

/**
 * Changes the font from Geist to Inter by replacing layout.tsx and globals.css files.
 */
export async function changeFont({ cwd }: { cwd: string }): Promise<void> {
    logger.info('Changing font to Inter...')

    const layoutPath = await findFilePath({
        cwd,
        possiblePaths: ['src/app/layout.tsx', 'app/layout.tsx'],
        fileDescription: 'layout',
    })

    if (!layoutPath) {
        logger.warn('Could not find layout file')
        return
    }

    try {
        // Write new layout.tsx
        await writeFile(layoutPath, NEW_LAYOUT_CONTENT, 'utf-8')
        logger.success('layout.tsx updated successfully')

        // Write new globals.css (in the same directory as layout.tsx)
        const globalsPath = join(dirname(layoutPath), 'globals.css')

        // Check if globals.css exists before replacing it
        if (await fileExists(globalsPath)) {
            await writeFile(globalsPath, NEW_GLOBALS_CSS_CONTENT, 'utf-8')
            logger.success('globals.css updated successfully')
        } else {
            logger.warn('globals.css not found, skipping')
        }
    } catch (error) {
        logger.error('Failed to change font. Please update files manually.', { error })
    }
}
